run:
  timeout: 5m

output:
  sort-results: true

linters:
  enable:
    - gofumpt
    - goimports
    - revive
    - misspell
    - goheader
    - whitespace
    - unused
    - stylecheck

issues:
  max-same-issues: 0
  exclude-dirs:
    - (^|/)usr/local($|/)
    - (^|/)pkg/mod($|/)
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck


linters-settings:
  gofumpt:
    extra-rules: true