name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'golang:1.23'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: "do not stamp the binaries with the version control system"
        run: go env -w GOFLAGS="-buildvcs=false"

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version:  v1.60
          skip-pkg-cache: true

      - name: Run tests
        run: make test